version: '3.8'

services:
  app:
    build: .
    container_name: jonathancarvalho039/notification-order-hub:latest
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATA_BASE_URL: jdbc:mysql://order-hub-db.cy356uxitvhj.us-east-1.rds.amazonaws.com:3306/order_hub?allowPublicKeyRetrieval=true&sslMode=DISABLED&serverTimezone=UTC
      DATA_BASE_USERNAME: orderhub
      DATA_BASE_PASSWORD: orderhub
    ports:
      - "8080:8080"
