server:
  port: 8080
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: notification-order-hub

  datasource:
    url: ${DATA_BASE_URL}
    username: ${DATA_BASE_USERNAME}
    password: ${DATA_BASE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          show_sql: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true

