server:
  port: 8080
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: notification-order-hub

aws:
  sqs:
    endpoint: ""
    queue:
      name: ${QUEUE_NAME:notification-orderhub}

  region: ${AWS_REGION:us-east-1}
  access-key-id: ${AWS_ACCESS_KEY_ID:AKIA3FRRJEMNRYCSBOW3}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY}

